### ISSUE TITLE
Configurable nav links block

### ISSUE THREAD

**Issue by CMTV** [math-it/book#1]
Make a configurable top nav links block. The links with FA 5 icons can be defined in `mkdocs.yml` block under `extra` configuration option. Example:

```yml
extra:
    links:
        - icon: 'far fa-comments'
          name: 'Forum'
          href: 'https:/google.com'
```
